service: alexa-btc-at-skill

frameworkVersion: ">=1.4.0 <2.0.0"

provider:
  name: aws
  runtime: python2.7

functions:
  luckyNumber:
    handler: lambda_function.lambda_handler
    events:
      - alexaSkill